# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'LeanMessageDemo' do
    pod 'AVOSCloud' , '3.1.2.9'
    pod 'AVOSCloudIM', '3.1.2.9'
    pod 'JSQMessagesViewController' 
end

target 'LeanMessageDemoTests' do

end

