# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'LeanMessageDemo' do
    pod 'AVOSCloud'
    pod 'AVOSCloudIM'
end

target 'LeanMessageDemoTests' do

end

